package pe

const (
	MAX_NUMBER_OF_SECTIONS           = 1000
	MAX_WIN_CERTIFICATE_LENGTH       = 1024 * 1024
	MAX_IMPORT_TABLE_LENGTH          = 10 * 1024
	MAX_RESOURCE_BLOCKS              = 10 * 1024
	MAX_RESOURCE_DIRECTORY_LENGTH    = 100
	MAX_MESSAGE_LENGTH               = 10 * 1024
	MAX_MESSAGES                     = 100 * 1024
	MAX_RESOURCE_STRING_TABLE_LENGTH = 100 * 1024

	IMAGE_DIRECTORY_ENTRY_ARCHITECTURE   = 7
	IMAGE_DIRECTORY_ENTRY_BASERELOC      = 5
	IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT   = 11
	IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 14
	IMAGE_DIRECTORY_ENTRY_DEBUG          = 6
	IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT   = 13
	IMAGE_DIRECTORY_ENTRY_EXCEPTION      = 3
	IMAGE_DIRECTORY_ENTRY_EXPORT         = 0
	IMAGE_DIRECTORY_ENTRY_GLOBALPTR      = 8
	IMAGE_DIRECTORY_ENTRY_IAT            = 12
	IMAGE_DIRECTORY_ENTRY_IMPORT         = 1
	IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG    = 10
	IMAGE_DIRECTORY_ENTRY_RESOURCE       = 2
	IMAGE_DIRECTORY_ENTRY_SECURITY       = 4
	IMAGE_DIRECTORY_ENTRY_TLS            = 9
)
