package pe

// Autogenerated code from pe_profile.json. Do not edit.

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
	"sort"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

var (
	// Depending on autogenerated code we may use this. Add a reference
	// to shut the compiler up.
	_ = bytes.MinRead
	_ = fmt.Sprintf
	_ = utf16.Decode
	_ = binary.LittleEndian
	_ = utf8.RuneError
	_ = sort.Strings
	_ = strings.Join
	_ = io.Copy
)

func indent(text string) string {
	result := []string{}
	lines := strings.Split(text, "\n")
	for _, line := range lines {
		result = append(result, "  "+line)
	}
	return strings.Join(result, "\n")
}

type PeProfile struct {
	Off_CV_RSDS_HEADER_Signature                         int64
	Off_CV_RSDS_HEADER_GUID                              int64
	Off_CV_RSDS_HEADER_Age                               int64
	Off_CV_RSDS_HEADER_Filename                          int64
	Off_MESSAGE_RESOURCE_BLOCK_LowId                     int64
	Off_MESSAGE_RESOURCE_BLOCK_HighId                    int64
	Off_MESSAGE_RESOURCE_BLOCK_OffsetToEntries           int64
	Off_MESSAGE_RESOURCE_DATA_NumberOfBlocks             int64
	Off_MESSAGE_RESOURCE_DATA__Blocks                    int64
	Off_MESSAGE_RESOURCE_ENTRY_Length                    int64
	Off_MESSAGE_RESOURCE_ENTRY_Flags                     int64
	Off_MESSAGE_RESOURCE_ENTRY_Text                      int64
	Off_PrefixedString_Length                            int64
	Off_PrefixedString__Buffer                           int64
	Off_ResourceString_Length                            int64
	Off_ResourceString_ValueLength                       int64
	Off_ResourceString_Type                              int64
	Off_ResourceString_Key                               int64
	Off_StringFileInfo_Length                            int64
	Off_StringFileInfo_ValueLength                       int64
	Off_StringFileInfo_Type                              int64
	Off_StringFileInfo_Key                               int64
	Off_StringTable_Length                               int64
	Off_StringTable_ValueLength                          int64
	Off_StringTable_Type                                 int64
	Off_StringTable_Key                                  int64
	Off_VS_VERSIONINFO_Length                            int64
	Off_VS_VERSIONINFO_ValueLength                       int64
	Off_VS_VERSIONINFO_Type                              int64
	Off_VS_VERSIONINFO_szKey                             int64
	Off_GUID_Data1                                       int64
	Off_GUID_Data2                                       int64
	Off_GUID_Data3                                       int64
	Off_GUID_Data4                                       int64
	Off_IMAGE_DATA_DIRECTORY_DirSize                     int64
	Off_IMAGE_DATA_DIRECTORY_VirtualAddress              int64
	Off_IMAGE_DEBUG_DIRECTORY_AddressOfRawData           int64
	Off_IMAGE_DEBUG_DIRECTORY_TimeDateStamp              int64
	Off_IMAGE_DEBUG_DIRECTORY_Type                       int64
	Off_IMAGE_DOS_HEADER_E_lfanew                        int64
	Off_IMAGE_DOS_HEADER_E_magic                         int64
	Off_IMAGE_EXPORT_DIRECTORY_AddressOfFunctions        int64
	Off_IMAGE_EXPORT_DIRECTORY_AddressOfNameOrdinals     int64
	Off_IMAGE_EXPORT_DIRECTORY_AddressOfNames            int64
	Off_IMAGE_EXPORT_DIRECTORY_Base                      int64
	Off_IMAGE_EXPORT_DIRECTORY_Name                      int64
	Off_IMAGE_EXPORT_DIRECTORY_NumberOfFunctions         int64
	Off_IMAGE_EXPORT_DIRECTORY_NumberOfNames             int64
	Off_IMAGE_FILE_HEADER_Characteristics                int64
	Off_IMAGE_FILE_HEADER_Machine                        int64
	Off_IMAGE_FILE_HEADER_NumberOfSections               int64
	Off_IMAGE_FILE_HEADER_SizeOfOptionalHeader           int64
	Off_IMAGE_FILE_HEADER_TimeDateStamp                  int64
	Off_IMAGE_IMPORT_BY_NAME_Name                        int64
	Off_IMAGE_IMPORT_DESCRIPTOR_Characteristics          int64
	Off_IMAGE_IMPORT_DESCRIPTOR_Name                     int64
	Off_IMAGE_IMPORT_DESCRIPTOR_OriginalFirstThunk       int64
	Off_IMAGE_NT_HEADERS_FileHeader                      int64
	Off_IMAGE_NT_HEADERS_OptionalHeader                  int64
	Off_IMAGE_NT_HEADERS_Signature                       int64
	Off_IMAGE_OPTIONAL_HEADER_DataDirectory              int64
	Off_IMAGE_OPTIONAL_HEADER_ImageBase                  int64
	Off_IMAGE_OPTIONAL_HEADER_Magic                      int64
	Off_IMAGE_OPTIONAL_HEADER64_DataDirectory            int64
	Off_IMAGE_OPTIONAL_HEADER64_ImageBase                int64
	Off_IMAGE_OPTIONAL_HEADER64_Magic                    int64
	Off_IMAGE_RESOURCE_DATA_ENTRY_OffsetToData           int64
	Off_IMAGE_RESOURCE_DATA_ENTRY_DataSize               int64
	Off_IMAGE_RESOURCE_DATA_ENTRY_CodePage               int64
	Off_IMAGE_RESOURCE_DIRECTORY_NumberOfIdEntries       int64
	Off_IMAGE_RESOURCE_DIRECTORY_NumberOfNamedEntries    int64
	Off_IMAGE_RESOURCE_DIRECTORY__Entries                int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_Type              int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_DataIsDirectory   int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_NameIsString      int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_NameOffset        int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_OffsetToData      int64
	Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_OffsetToDirectory int64
	Off_IMAGE_SECTION_HEADER_Characteristics             int64
	Off_IMAGE_SECTION_HEADER_Name                        int64
	Off_IMAGE_SECTION_HEADER_PointerToRawData            int64
	Off_IMAGE_SECTION_HEADER_SizeOfRawData               int64
	Off_IMAGE_SECTION_HEADER_VirtualAddress              int64
	Off_IMAGE_THUNK_DATA32_AddressOfData                 int64
	Off_IMAGE_THUNK_DATA32_ForwarderString               int64
	Off_IMAGE_THUNK_DATA32_Function                      int64
	Off_IMAGE_THUNK_DATA32_Ordinal                       int64
	Off_IMAGE_THUNK_DATA64_AddressOfData                 int64
	Off_IMAGE_THUNK_DATA64_ForwarderString               int64
	Off_IMAGE_THUNK_DATA64_Function                      int64
	Off_IMAGE_THUNK_DATA64_Ordinal                       int64
}

func NewPeProfile() *PeProfile {
	// Specific offsets can be tweaked to cater for slight version mismatches.
	self := &PeProfile{0, 4, 20, 24, 0, 4, 8, 0, 4, 0, 2, 4, 0, 2, 0, 2, 4, 6, 0, 2, 4, 6, 0, 2, 4, 6, 0, 2, 4, 6, 0, 4, 6, 8, 4, 0, 20, 4, 12, 60, 0, 28, 36, 32, 16, 12, 20, 24, 18, 0, 2, 16, 4, 2, 0, 12, 0, 4, 24, 0, 96, 28, 0, 112, 24, 0, 0, 4, 8, 14, 12, 16, 0, 4, 0, 0, 4, 4, 36, 0, 20, 16, 12, 0, 0, 0, 0, 0, 0, 0, 0}
	return self
}

func (self *PeProfile) CV_RSDS_HEADER(reader io.ReaderAt, offset int64) *CV_RSDS_HEADER {
	return &CV_RSDS_HEADER{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) MESSAGE_RESOURCE_BLOCK(reader io.ReaderAt, offset int64) *MESSAGE_RESOURCE_BLOCK {
	return &MESSAGE_RESOURCE_BLOCK{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) MESSAGE_RESOURCE_DATA(reader io.ReaderAt, offset int64) *MESSAGE_RESOURCE_DATA {
	return &MESSAGE_RESOURCE_DATA{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) MESSAGE_RESOURCE_ENTRY(reader io.ReaderAt, offset int64) *MESSAGE_RESOURCE_ENTRY {
	return &MESSAGE_RESOURCE_ENTRY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) PrefixedString(reader io.ReaderAt, offset int64) *PrefixedString {
	return &PrefixedString{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) ResourceString(reader io.ReaderAt, offset int64) *ResourceString {
	return &ResourceString{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) StringFileInfo(reader io.ReaderAt, offset int64) *StringFileInfo {
	return &StringFileInfo{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) StringTable(reader io.ReaderAt, offset int64) *StringTable {
	return &StringTable{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) VS_VERSIONINFO(reader io.ReaderAt, offset int64) *VS_VERSIONINFO {
	return &VS_VERSIONINFO{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) GUID(reader io.ReaderAt, offset int64) *GUID {
	return &GUID{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_DATA_DIRECTORY(reader io.ReaderAt, offset int64) *IMAGE_DATA_DIRECTORY {
	return &IMAGE_DATA_DIRECTORY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_DEBUG_DIRECTORY(reader io.ReaderAt, offset int64) *IMAGE_DEBUG_DIRECTORY {
	return &IMAGE_DEBUG_DIRECTORY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_DOS_HEADER(reader io.ReaderAt, offset int64) *IMAGE_DOS_HEADER {
	return &IMAGE_DOS_HEADER{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_EXPORT_DIRECTORY(reader io.ReaderAt, offset int64) *IMAGE_EXPORT_DIRECTORY {
	return &IMAGE_EXPORT_DIRECTORY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_FILE_HEADER(reader io.ReaderAt, offset int64) *IMAGE_FILE_HEADER {
	return &IMAGE_FILE_HEADER{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_IMPORT_BY_NAME(reader io.ReaderAt, offset int64) *IMAGE_IMPORT_BY_NAME {
	return &IMAGE_IMPORT_BY_NAME{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_IMPORT_DESCRIPTOR(reader io.ReaderAt, offset int64) *IMAGE_IMPORT_DESCRIPTOR {
	return &IMAGE_IMPORT_DESCRIPTOR{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_NT_HEADERS(reader io.ReaderAt, offset int64) *IMAGE_NT_HEADERS {
	return &IMAGE_NT_HEADERS{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_OPTIONAL_HEADER(reader io.ReaderAt, offset int64) *IMAGE_OPTIONAL_HEADER {
	return &IMAGE_OPTIONAL_HEADER{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_OPTIONAL_HEADER64(reader io.ReaderAt, offset int64) *IMAGE_OPTIONAL_HEADER64 {
	return &IMAGE_OPTIONAL_HEADER64{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_RESOURCE_DATA_ENTRY(reader io.ReaderAt, offset int64) *IMAGE_RESOURCE_DATA_ENTRY {
	return &IMAGE_RESOURCE_DATA_ENTRY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_RESOURCE_DIRECTORY(reader io.ReaderAt, offset int64) *IMAGE_RESOURCE_DIRECTORY {
	return &IMAGE_RESOURCE_DIRECTORY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_RESOURCE_DIRECTORY_ENTRY(reader io.ReaderAt, offset int64) *IMAGE_RESOURCE_DIRECTORY_ENTRY {
	return &IMAGE_RESOURCE_DIRECTORY_ENTRY{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_SECTION_HEADER(reader io.ReaderAt, offset int64) *IMAGE_SECTION_HEADER {
	return &IMAGE_SECTION_HEADER{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_THUNK_DATA32(reader io.ReaderAt, offset int64) *IMAGE_THUNK_DATA32 {
	return &IMAGE_THUNK_DATA32{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) IMAGE_THUNK_DATA64(reader io.ReaderAt, offset int64) *IMAGE_THUNK_DATA64 {
	return &IMAGE_THUNK_DATA64{Reader: reader, Offset: offset, Profile: self}
}

func (self *PeProfile) TagVS_FIXEDFILEINFO(reader io.ReaderAt, offset int64) *TagVS_FIXEDFILEINFO {
	return &TagVS_FIXEDFILEINFO{Reader: reader, Offset: offset, Profile: self}
}

type CV_RSDS_HEADER struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *CV_RSDS_HEADER) Size() int {
	return 28
}

func (self *CV_RSDS_HEADER) Signature() string {
	return ParseString(self.Reader, self.Profile.Off_CV_RSDS_HEADER_Signature+self.Offset, 4)
}

func (self *CV_RSDS_HEADER) GUID() *GUID {
	return self.Profile.GUID(self.Reader, self.Profile.Off_CV_RSDS_HEADER_GUID+self.Offset)
}

func (self *CV_RSDS_HEADER) Age() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_CV_RSDS_HEADER_Age+self.Offset)
}

func (self *CV_RSDS_HEADER) Filename() string {
	return ParseTerminatedString(self.Reader, self.Profile.Off_CV_RSDS_HEADER_Filename+self.Offset)
}
func (self *CV_RSDS_HEADER) DebugString() string {
	result := fmt.Sprintf("struct CV_RSDS_HEADER @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Signature: %v\n", string(self.Signature()))
	result += fmt.Sprintf("  GUID: {\n%v}\n", indent(self.GUID().DebugString()))
	result += fmt.Sprintf("  Age: %#0x\n", self.Age())
	result += fmt.Sprintf("  Filename: %v\n", string(self.Filename()))
	return result
}

type MESSAGE_RESOURCE_BLOCK struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *MESSAGE_RESOURCE_BLOCK) Size() int {
	return 12
}

func (self *MESSAGE_RESOURCE_BLOCK) LowId() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_BLOCK_LowId+self.Offset)
}

func (self *MESSAGE_RESOURCE_BLOCK) HighId() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_BLOCK_HighId+self.Offset)
}

func (self *MESSAGE_RESOURCE_BLOCK) OffsetToEntries() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_BLOCK_OffsetToEntries+self.Offset)
}
func (self *MESSAGE_RESOURCE_BLOCK) DebugString() string {
	result := fmt.Sprintf("struct MESSAGE_RESOURCE_BLOCK @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  LowId: %#0x\n", self.LowId())
	result += fmt.Sprintf("  HighId: %#0x\n", self.HighId())
	result += fmt.Sprintf("  OffsetToEntries: %#0x\n", self.OffsetToEntries())
	return result
}

type MESSAGE_RESOURCE_DATA struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *MESSAGE_RESOURCE_DATA) Size() int {
	return 0
}

func (self *MESSAGE_RESOURCE_DATA) NumberOfBlocks() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_DATA_NumberOfBlocks+self.Offset)
}

func (self *MESSAGE_RESOURCE_DATA) _Blocks() []*MESSAGE_RESOURCE_BLOCK {
	return ParseArray_MESSAGE_RESOURCE_BLOCK(self.Profile, self.Reader, self.Profile.Off_MESSAGE_RESOURCE_DATA__Blocks+self.Offset, 0)
}
func (self *MESSAGE_RESOURCE_DATA) DebugString() string {
	result := fmt.Sprintf("struct MESSAGE_RESOURCE_DATA @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  NumberOfBlocks: %#0x\n", self.NumberOfBlocks())
	return result
}

type MESSAGE_RESOURCE_ENTRY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *MESSAGE_RESOURCE_ENTRY) Size() int {
	return 0
}

func (self *MESSAGE_RESOURCE_ENTRY) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_ENTRY_Length+self.Offset)
}

func (self *MESSAGE_RESOURCE_ENTRY) Flags() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_ENTRY_Flags+self.Offset)
}

func (self *MESSAGE_RESOURCE_ENTRY) Text() string {
	return ParseTerminatedUTF16String(self.Reader, self.Profile.Off_MESSAGE_RESOURCE_ENTRY_Text+self.Offset)
}
func (self *MESSAGE_RESOURCE_ENTRY) DebugString() string {
	result := fmt.Sprintf("struct MESSAGE_RESOURCE_ENTRY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  Flags: %#0x\n", self.Flags())
	result += fmt.Sprintf("  Text: %v\n", string(self.Text()))
	return result
}

type PrefixedString struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *PrefixedString) Size() int {
	return 2
}

func (self *PrefixedString) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_PrefixedString_Length+self.Offset)
}

func (self *PrefixedString) _Buffer() byte {
	return ParseUint8(self.Reader, self.Profile.Off_PrefixedString__Buffer+self.Offset)
}
func (self *PrefixedString) DebugString() string {
	result := fmt.Sprintf("struct PrefixedString @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  _Buffer: %#0x\n", self._Buffer())
	return result
}

type ResourceString struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *ResourceString) Size() int {
	return 0
}

func (self *ResourceString) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_ResourceString_Length+self.Offset)
}

func (self *ResourceString) ValueLength() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_ResourceString_ValueLength+self.Offset)
}

func (self *ResourceString) Type() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_ResourceString_Type+self.Offset)
}

func (self *ResourceString) Key() string {
	return ParseTerminatedUTF16String(self.Reader, self.Profile.Off_ResourceString_Key+self.Offset)
}
func (self *ResourceString) DebugString() string {
	result := fmt.Sprintf("struct ResourceString @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  ValueLength: %#0x\n", self.ValueLength())
	result += fmt.Sprintf("  Type: %#0x\n", self.Type())
	result += fmt.Sprintf("  Key: %v\n", string(self.Key()))
	return result
}

type StringFileInfo struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *StringFileInfo) Size() int {
	return 0
}

func (self *StringFileInfo) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringFileInfo_Length+self.Offset)
}

func (self *StringFileInfo) ValueLength() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringFileInfo_ValueLength+self.Offset)
}

func (self *StringFileInfo) Type() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringFileInfo_Type+self.Offset)
}

func (self *StringFileInfo) Key() string {
	return ParseTerminatedUTF16String(self.Reader, self.Profile.Off_StringFileInfo_Key+self.Offset)
}
func (self *StringFileInfo) DebugString() string {
	result := fmt.Sprintf("struct StringFileInfo @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  ValueLength: %#0x\n", self.ValueLength())
	result += fmt.Sprintf("  Type: %#0x\n", self.Type())
	result += fmt.Sprintf("  Key: %v\n", string(self.Key()))
	return result
}

type StringTable struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *StringTable) Size() int {
	return 0
}

func (self *StringTable) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringTable_Length+self.Offset)
}

func (self *StringTable) ValueLength() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringTable_ValueLength+self.Offset)
}

func (self *StringTable) Type() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_StringTable_Type+self.Offset)
}

func (self *StringTable) Key() string {
	return ParseUTF16String(self.Reader, self.Profile.Off_StringTable_Key+self.Offset, 16)
}
func (self *StringTable) DebugString() string {
	result := fmt.Sprintf("struct StringTable @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  ValueLength: %#0x\n", self.ValueLength())
	result += fmt.Sprintf("  Type: %#0x\n", self.Type())
	result += fmt.Sprintf("  Key: %v\n", string(self.Key()))
	return result
}

type VS_VERSIONINFO struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *VS_VERSIONINFO) Size() int {
	return 6
}

func (self *VS_VERSIONINFO) Length() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_VS_VERSIONINFO_Length+self.Offset)
}

func (self *VS_VERSIONINFO) ValueLength() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_VS_VERSIONINFO_ValueLength+self.Offset)
}

func (self *VS_VERSIONINFO) Type() *Enumeration {
	value := ParseUint16(self.Reader, self.Profile.Off_VS_VERSIONINFO_Type+self.Offset)
	name := "Unknown"
	switch value {

	case 0:
		name = "Binary"

	case 1:
		name = "Text"
	}
	return &Enumeration{Value: uint64(value), Name: name}
}

func (self *VS_VERSIONINFO) szKey() string {
	return ParseUTF16String(self.Reader, self.Profile.Off_VS_VERSIONINFO_szKey+self.Offset, 32)
}
func (self *VS_VERSIONINFO) DebugString() string {
	result := fmt.Sprintf("struct VS_VERSIONINFO @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Length: %#0x\n", self.Length())
	result += fmt.Sprintf("  ValueLength: %#0x\n", self.ValueLength())
	result += fmt.Sprintf("  Type: %v\n", self.Type().DebugString())
	result += fmt.Sprintf("  szKey: %v\n", string(self.szKey()))
	return result
}

type GUID struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *GUID) Size() int {
	return 16
}

func (self *GUID) Data1() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_GUID_Data1+self.Offset)
}

func (self *GUID) Data2() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_GUID_Data2+self.Offset)
}

func (self *GUID) Data3() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_GUID_Data3+self.Offset)
}

func (self *GUID) Data4() []byte {
	return ParseArray_byte(self.Profile, self.Reader, self.Profile.Off_GUID_Data4+self.Offset, 8)
}
func (self *GUID) DebugString() string {
	result := fmt.Sprintf("struct GUID @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Data1: %#0x\n", self.Data1())
	result += fmt.Sprintf("  Data2: %#0x\n", self.Data2())
	result += fmt.Sprintf("  Data3: %#0x\n", self.Data3())
	return result
}

type IMAGE_DATA_DIRECTORY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_DATA_DIRECTORY) Size() int {
	return 8
}

func (self *IMAGE_DATA_DIRECTORY) DirSize() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_DATA_DIRECTORY_DirSize+self.Offset)
}

func (self *IMAGE_DATA_DIRECTORY) VirtualAddress() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_DATA_DIRECTORY_VirtualAddress+self.Offset)
}
func (self *IMAGE_DATA_DIRECTORY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_DATA_DIRECTORY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  DirSize: %#0x\n", self.DirSize())
	result += fmt.Sprintf("  VirtualAddress: %#0x\n", self.VirtualAddress())
	return result
}

type IMAGE_DEBUG_DIRECTORY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_DEBUG_DIRECTORY) Size() int {
	return 24
}

func (self *IMAGE_DEBUG_DIRECTORY) AddressOfRawData() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_DEBUG_DIRECTORY_AddressOfRawData+self.Offset)
}

func (self *IMAGE_DEBUG_DIRECTORY) TimeDateStamp() *UnixTimeStamp {
	return self.Profile.UnixTimeStamp(self.Reader, self.Profile.Off_IMAGE_DEBUG_DIRECTORY_TimeDateStamp+self.Offset)
}

func (self *IMAGE_DEBUG_DIRECTORY) Type() *Enumeration {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_DEBUG_DIRECTORY_Type+self.Offset)
	name := "Unknown"
	switch value {

	case 0:
		name = "IMAGE_DEBUG_TYPE_UNKNOWN"

	case 1:
		name = "IMAGE_DEBUG_TYPE_COFF"

	case 2:
		name = "IMAGE_DEBUG_TYPE_CODEVIEW"

	case 3:
		name = "IMAGE_DEBUG_TYPE_FPO"

	case 4:
		name = "IMAGE_DEBUG_TYPE_MISC"

	case 5:
		name = "IMAGE_DEBUG_TYPE_EXCEPTION"

	case 6:
		name = "IMAGE_DEBUG_TYPE_FIXUP"

	case 7:
		name = "IMAGE_DEBUG_TYPE_OMAP_TO_SRC"

	case 8:
		name = "IMAGE_DEBUG_TYPE_OMAP_FROM_SRC"

	case 9:
		name = "IMAGE_DEBUG_TYPE_BORLAND"

	case 10:
		name = "IMAGE_DEBUG_TYPE_RESERVED"
	}
	return &Enumeration{Value: uint64(value), Name: name}
}

func (self *IMAGE_DEBUG_DIRECTORY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_DEBUG_DIRECTORY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  AddressOfRawData: %#0x\n", self.AddressOfRawData())
	result += fmt.Sprintf("  TimeDateStamp: {\n%v}\n", indent(self.TimeDateStamp().DebugString()))
	result += fmt.Sprintf("  Type: %v\n", self.Type().DebugString())
	return result
}

type IMAGE_DOS_HEADER struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_DOS_HEADER) Size() int {
	return 64
}

func (self *IMAGE_DOS_HEADER) E_lfanew() int32 {
	return ParseInt32(self.Reader, self.Profile.Off_IMAGE_DOS_HEADER_E_lfanew+self.Offset)
}

func (self *IMAGE_DOS_HEADER) E_magic() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_DOS_HEADER_E_magic+self.Offset)
}
func (self *IMAGE_DOS_HEADER) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_DOS_HEADER @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  E_lfanew: %#0x\n", self.E_lfanew())
	result += fmt.Sprintf("  E_magic: %#0x\n", self.E_magic())
	return result
}

type IMAGE_EXPORT_DIRECTORY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_EXPORT_DIRECTORY) Size() int {
	return 40
}

func (self *IMAGE_EXPORT_DIRECTORY) AddressOfFunctions() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_AddressOfFunctions+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) AddressOfNameOrdinals() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_AddressOfNameOrdinals+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) AddressOfNames() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_AddressOfNames+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) Base() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_Base+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) Name() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_Name+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) NumberOfFunctions() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_NumberOfFunctions+self.Offset)
}

func (self *IMAGE_EXPORT_DIRECTORY) NumberOfNames() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_EXPORT_DIRECTORY_NumberOfNames+self.Offset)
}
func (self *IMAGE_EXPORT_DIRECTORY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_EXPORT_DIRECTORY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  AddressOfFunctions: %#0x\n", self.AddressOfFunctions())
	result += fmt.Sprintf("  AddressOfNameOrdinals: %#0x\n", self.AddressOfNameOrdinals())
	result += fmt.Sprintf("  AddressOfNames: %#0x\n", self.AddressOfNames())
	result += fmt.Sprintf("  Base: %#0x\n", self.Base())
	result += fmt.Sprintf("  Name: %#0x\n", self.Name())
	result += fmt.Sprintf("  NumberOfFunctions: %#0x\n", self.NumberOfFunctions())
	result += fmt.Sprintf("  NumberOfNames: %#0x\n", self.NumberOfNames())
	return result
}

type IMAGE_FILE_HEADER struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_FILE_HEADER) Size() int {
	return 20
}

func (self *IMAGE_FILE_HEADER) Characteristics() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_FILE_HEADER_Characteristics+self.Offset)
}

func (self *IMAGE_FILE_HEADER) Machine() *Enumeration {
	value := ParseUint16(self.Reader, self.Profile.Off_IMAGE_FILE_HEADER_Machine+self.Offset)
	name := "Unknown"
	switch value {

	case 332:
		name = "IMAGE_FILE_MACHINE_I386"

	case 448:
		name = "IMAGE_FILE_MACHINE_ARM"

	case 512:
		name = "IMAGE_FILE_MACHINE_IA64"

	case 34404:
		name = "IMAGE_FILE_MACHINE_AMD64"
	}
	return &Enumeration{Value: uint64(value), Name: name}
}

func (self *IMAGE_FILE_HEADER) NumberOfSections() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_FILE_HEADER_NumberOfSections+self.Offset)
}

func (self *IMAGE_FILE_HEADER) SizeOfOptionalHeader() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_FILE_HEADER_SizeOfOptionalHeader+self.Offset)
}

func (self *IMAGE_FILE_HEADER) TimeDateStamp() *UnixTimeStamp {
	return self.Profile.UnixTimeStamp(self.Reader, self.Profile.Off_IMAGE_FILE_HEADER_TimeDateStamp+self.Offset)
}
func (self *IMAGE_FILE_HEADER) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_FILE_HEADER @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Characteristics: %#0x\n", self.Characteristics())
	result += fmt.Sprintf("  Machine: %v\n", self.Machine().DebugString())
	result += fmt.Sprintf("  NumberOfSections: %#0x\n", self.NumberOfSections())
	result += fmt.Sprintf("  SizeOfOptionalHeader: %#0x\n", self.SizeOfOptionalHeader())
	result += fmt.Sprintf("  TimeDateStamp: {\n%v}\n", indent(self.TimeDateStamp().DebugString()))
	return result
}

type IMAGE_IMPORT_BY_NAME struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_IMPORT_BY_NAME) Size() int {
	return 4
}

func (self *IMAGE_IMPORT_BY_NAME) Name() string {
	return ParseTerminatedString(self.Reader, self.Profile.Off_IMAGE_IMPORT_BY_NAME_Name+self.Offset)
}
func (self *IMAGE_IMPORT_BY_NAME) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_IMPORT_BY_NAME @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Name: %v\n", string(self.Name()))
	return result
}

type IMAGE_IMPORT_DESCRIPTOR struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_IMPORT_DESCRIPTOR) Size() int {
	return 20
}

func (self *IMAGE_IMPORT_DESCRIPTOR) Characteristics() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_IMPORT_DESCRIPTOR_Characteristics+self.Offset)
}

func (self *IMAGE_IMPORT_DESCRIPTOR) Name() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_IMPORT_DESCRIPTOR_Name+self.Offset)
}

func (self *IMAGE_IMPORT_DESCRIPTOR) OriginalFirstThunk() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_IMPORT_DESCRIPTOR_OriginalFirstThunk+self.Offset)
}
func (self *IMAGE_IMPORT_DESCRIPTOR) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_IMPORT_DESCRIPTOR @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Characteristics: %#0x\n", self.Characteristics())
	result += fmt.Sprintf("  Name: %#0x\n", self.Name())
	result += fmt.Sprintf("  OriginalFirstThunk: %#0x\n", self.OriginalFirstThunk())
	return result
}

type IMAGE_NT_HEADERS struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_NT_HEADERS) Size() int {
	return 248
}

func (self *IMAGE_NT_HEADERS) FileHeader() *IMAGE_FILE_HEADER {
	return self.Profile.IMAGE_FILE_HEADER(self.Reader, self.Profile.Off_IMAGE_NT_HEADERS_FileHeader+self.Offset)
}

func (self *IMAGE_NT_HEADERS) OptionalHeader() *IMAGE_OPTIONAL_HEADER {
	return self.Profile.IMAGE_OPTIONAL_HEADER(self.Reader, self.Profile.Off_IMAGE_NT_HEADERS_OptionalHeader+self.Offset)
}

func (self *IMAGE_NT_HEADERS) Signature() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_NT_HEADERS_Signature+self.Offset)
}
func (self *IMAGE_NT_HEADERS) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_NT_HEADERS @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  FileHeader: {\n%v}\n", indent(self.FileHeader().DebugString()))
	result += fmt.Sprintf("  OptionalHeader: {\n%v}\n", indent(self.OptionalHeader().DebugString()))
	result += fmt.Sprintf("  Signature: %#0x\n", self.Signature())
	return result
}

type IMAGE_OPTIONAL_HEADER struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_OPTIONAL_HEADER) Size() int {
	return 224
}

func (self *IMAGE_OPTIONAL_HEADER) DataDirectory() []*IMAGE_DATA_DIRECTORY {
	return ParseArray_IMAGE_DATA_DIRECTORY(self.Profile, self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER_DataDirectory+self.Offset, 128)
}

func (self *IMAGE_OPTIONAL_HEADER) ImageBase() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER_ImageBase+self.Offset)
}

func (self *IMAGE_OPTIONAL_HEADER) Magic() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER_Magic+self.Offset)
}
func (self *IMAGE_OPTIONAL_HEADER) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_OPTIONAL_HEADER @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  ImageBase: %#0x\n", self.ImageBase())
	result += fmt.Sprintf("  Magic: %#0x\n", self.Magic())
	return result
}

type IMAGE_OPTIONAL_HEADER64 struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_OPTIONAL_HEADER64) Size() int {
	return 240
}

func (self *IMAGE_OPTIONAL_HEADER64) DataDirectory() []*IMAGE_DATA_DIRECTORY {
	return ParseArray_IMAGE_DATA_DIRECTORY(self.Profile, self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER64_DataDirectory+self.Offset, 128)
}

func (self *IMAGE_OPTIONAL_HEADER64) ImageBase() uint64 {
	return ParseUint64(self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER64_ImageBase+self.Offset)
}

func (self *IMAGE_OPTIONAL_HEADER64) Magic() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_OPTIONAL_HEADER64_Magic+self.Offset)
}
func (self *IMAGE_OPTIONAL_HEADER64) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_OPTIONAL_HEADER64 @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  ImageBase: %#0x\n", self.ImageBase())
	result += fmt.Sprintf("  Magic: %#0x\n", self.Magic())
	return result
}

type IMAGE_RESOURCE_DATA_ENTRY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_RESOURCE_DATA_ENTRY) Size() int {
	return 16
}

func (self *IMAGE_RESOURCE_DATA_ENTRY) OffsetToData() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DATA_ENTRY_OffsetToData+self.Offset)
}

func (self *IMAGE_RESOURCE_DATA_ENTRY) DataSize() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DATA_ENTRY_DataSize+self.Offset)
}

func (self *IMAGE_RESOURCE_DATA_ENTRY) CodePage() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DATA_ENTRY_CodePage+self.Offset)
}
func (self *IMAGE_RESOURCE_DATA_ENTRY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_RESOURCE_DATA_ENTRY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  OffsetToData: %#0x\n", self.OffsetToData())
	result += fmt.Sprintf("  DataSize: %#0x\n", self.DataSize())
	result += fmt.Sprintf("  CodePage: %#0x\n", self.CodePage())
	return result
}

type IMAGE_RESOURCE_DIRECTORY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_RESOURCE_DIRECTORY) Size() int {
	return 16
}

func (self *IMAGE_RESOURCE_DIRECTORY) NumberOfIdEntries() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_NumberOfIdEntries+self.Offset)
}

func (self *IMAGE_RESOURCE_DIRECTORY) NumberOfNamedEntries() uint16 {
	return ParseUint16(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_NumberOfNamedEntries+self.Offset)
}

func (self *IMAGE_RESOURCE_DIRECTORY) _Entries() []*IMAGE_RESOURCE_DIRECTORY_ENTRY {
	return ParseArray_IMAGE_RESOURCE_DIRECTORY_ENTRY(self.Profile, self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY__Entries+self.Offset, 0)
}
func (self *IMAGE_RESOURCE_DIRECTORY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_RESOURCE_DIRECTORY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  NumberOfIdEntries: %#0x\n", self.NumberOfIdEntries())
	result += fmt.Sprintf("  NumberOfNamedEntries: %#0x\n", self.NumberOfNamedEntries())
	return result
}

type IMAGE_RESOURCE_DIRECTORY_ENTRY struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) Size() int {
	return 8
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) Type() *Enumeration {
	value := ParseUint8(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_Type+self.Offset)
	name := "Unknown"
	switch value {

	case 1:
		name = "RT_CURSOR"

	case 2:
		name = "RT_BITMAP"

	case 3:
		name = "RT_ICON"

	case 4:
		name = "RT_MENU"

	case 5:
		name = "RT_DIALOG"

	case 6:
		name = "RT_STRING"

	case 7:
		name = "RT_FONTDIR"

	case 8:
		name = "RT_FONT"

	case 9:
		name = "RT_ACCELERATOR"

	case 10:
		name = "RT_RCDATA"

	case 11:
		name = "RT_MESSAGETABLE"

	case 12:
		name = "RT_GROUP_CURSOR"

	case 14:
		name = "RT_GROUP_ICON"

	case 16:
		name = "RT_VERSION"

	case 17:
		name = "RT_DLGINCLUDE"

	case 19:
		name = "RT_PLUGPLAY"

	case 20:
		name = "RT_VXD"

	case 21:
		name = "RT_ANICURSOR"

	case 22:
		name = "RT_ANIICON"

	case 23:
		name = "RT_HTML"

	case 24:
		name = "RT_MANIFEST"
	}
	return &Enumeration{Value: uint64(value), Name: name}
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) DataIsDirectory() uint64 {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_DataIsDirectory+self.Offset)
	return (uint64(value) & 0x7fffffffffffffff) >> 0x1f
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) NameIsString() uint64 {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_NameIsString+self.Offset)
	return (uint64(value) & 0x7fffffffffffffff) >> 0x1f
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) NameOffset() uint64 {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_NameOffset+self.Offset)
	return (uint64(value) & 0x7fffffff) >> 0x0
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) OffsetToData() uint64 {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_OffsetToData+self.Offset)
	return (uint64(value) & 0x7fffffff) >> 0x0
}

func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) OffsetToDirectory() uint64 {
	value := ParseUint32(self.Reader, self.Profile.Off_IMAGE_RESOURCE_DIRECTORY_ENTRY_OffsetToDirectory+self.Offset)
	return (uint64(value) & 0x7fffffff) >> 0x0
}
func (self *IMAGE_RESOURCE_DIRECTORY_ENTRY) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_RESOURCE_DIRECTORY_ENTRY @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Type: %v\n", self.Type().DebugString())
	result += fmt.Sprintf("  DataIsDirectory: %#0x\n", self.DataIsDirectory())
	result += fmt.Sprintf("  NameIsString: %#0x\n", self.NameIsString())
	result += fmt.Sprintf("  NameOffset: %#0x\n", self.NameOffset())
	result += fmt.Sprintf("  OffsetToData: %#0x\n", self.OffsetToData())
	result += fmt.Sprintf("  OffsetToDirectory: %#0x\n", self.OffsetToDirectory())
	return result
}

type IMAGE_SECTION_HEADER struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_SECTION_HEADER) Size() int {
	return 40
}

func (self *IMAGE_SECTION_HEADER) Characteristics() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_SECTION_HEADER_Characteristics+self.Offset)
}

func (self *IMAGE_SECTION_HEADER) Name() string {
	return ParseTerminatedString(self.Reader, self.Profile.Off_IMAGE_SECTION_HEADER_Name+self.Offset)
}

func (self *IMAGE_SECTION_HEADER) PointerToRawData() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_SECTION_HEADER_PointerToRawData+self.Offset)
}

func (self *IMAGE_SECTION_HEADER) SizeOfRawData() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_SECTION_HEADER_SizeOfRawData+self.Offset)
}

func (self *IMAGE_SECTION_HEADER) VirtualAddress() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_SECTION_HEADER_VirtualAddress+self.Offset)
}
func (self *IMAGE_SECTION_HEADER) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_SECTION_HEADER @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  Characteristics: %#0x\n", self.Characteristics())
	result += fmt.Sprintf("  Name: %v\n", string(self.Name()))
	result += fmt.Sprintf("  PointerToRawData: %#0x\n", self.PointerToRawData())
	result += fmt.Sprintf("  SizeOfRawData: %#0x\n", self.SizeOfRawData())
	result += fmt.Sprintf("  VirtualAddress: %#0x\n", self.VirtualAddress())
	return result
}

type IMAGE_THUNK_DATA32 struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_THUNK_DATA32) Size() int {
	return 4
}

func (self *IMAGE_THUNK_DATA32) AddressOfData() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA32_AddressOfData+self.Offset)
}

func (self *IMAGE_THUNK_DATA32) ForwarderString() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA32_ForwarderString+self.Offset)
}

func (self *IMAGE_THUNK_DATA32) Function() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA32_Function+self.Offset)
}

func (self *IMAGE_THUNK_DATA32) Ordinal() uint32 {
	return ParseUint32(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA32_Ordinal+self.Offset)
}
func (self *IMAGE_THUNK_DATA32) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_THUNK_DATA32 @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  AddressOfData: %#0x\n", self.AddressOfData())
	result += fmt.Sprintf("  ForwarderString: %#0x\n", self.ForwarderString())
	result += fmt.Sprintf("  Function: %#0x\n", self.Function())
	result += fmt.Sprintf("  Ordinal: %#0x\n", self.Ordinal())
	return result
}

type IMAGE_THUNK_DATA64 struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *IMAGE_THUNK_DATA64) Size() int {
	return 8
}

func (self *IMAGE_THUNK_DATA64) AddressOfData() uint64 {
	return ParseUint64(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA64_AddressOfData+self.Offset)
}

func (self *IMAGE_THUNK_DATA64) ForwarderString() uint64 {
	return ParseUint64(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA64_ForwarderString+self.Offset)
}

func (self *IMAGE_THUNK_DATA64) Function() uint64 {
	return ParseUint64(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA64_Function+self.Offset)
}

func (self *IMAGE_THUNK_DATA64) Ordinal() uint64 {
	return ParseUint64(self.Reader, self.Profile.Off_IMAGE_THUNK_DATA64_Ordinal+self.Offset)
}
func (self *IMAGE_THUNK_DATA64) DebugString() string {
	result := fmt.Sprintf("struct IMAGE_THUNK_DATA64 @ %#x:\n", self.Offset)
	result += fmt.Sprintf("  AddressOfData: %#0x\n", self.AddressOfData())
	result += fmt.Sprintf("  ForwarderString: %#0x\n", self.ForwarderString())
	result += fmt.Sprintf("  Function: %#0x\n", self.Function())
	result += fmt.Sprintf("  Ordinal: %#0x\n", self.Ordinal())
	return result
}

type TagVS_FIXEDFILEINFO struct {
	Reader  io.ReaderAt
	Offset  int64
	Profile *PeProfile
}

func (self *TagVS_FIXEDFILEINFO) Size() int {
	return 52
}
func (self *TagVS_FIXEDFILEINFO) DebugString() string {
	result := fmt.Sprintf("struct TagVS_FIXEDFILEINFO @ %#x:\n", self.Offset)
	return result
}

type Enumeration struct {
	Value uint64
	Name  string
}

func (self Enumeration) DebugString() string {
	return fmt.Sprintf("%s (%d)", self.Name, self.Value)
}

func ParseArray_IMAGE_DATA_DIRECTORY(profile *PeProfile, reader io.ReaderAt, offset int64, count int) []*IMAGE_DATA_DIRECTORY {
	result := []*IMAGE_DATA_DIRECTORY{}
	for i := 0; i < count; i++ {
		value := profile.IMAGE_DATA_DIRECTORY(reader, offset)
		result = append(result, value)
		offset += int64(value.Size())
	}
	return result
}

func ParseArray_IMAGE_RESOURCE_DIRECTORY_ENTRY(profile *PeProfile, reader io.ReaderAt, offset int64, count int) []*IMAGE_RESOURCE_DIRECTORY_ENTRY {
	result := []*IMAGE_RESOURCE_DIRECTORY_ENTRY{}
	for i := 0; i < count; i++ {
		value := profile.IMAGE_RESOURCE_DIRECTORY_ENTRY(reader, offset)
		result = append(result, value)
		offset += int64(value.Size())
	}
	return result
}

func ParseArray_MESSAGE_RESOURCE_BLOCK(profile *PeProfile, reader io.ReaderAt, offset int64, count int) []*MESSAGE_RESOURCE_BLOCK {
	result := []*MESSAGE_RESOURCE_BLOCK{}
	for i := 0; i < count; i++ {
		value := profile.MESSAGE_RESOURCE_BLOCK(reader, offset)
		result = append(result, value)
		offset += int64(value.Size())
	}
	return result
}

func ParseArray_byte(profile *PeProfile, reader io.ReaderAt, offset int64, count int) []byte {
	result := []byte{}
	for i := 0; i < count; i++ {
		value := ParseUint8(reader, offset)
		result = append(result, value)
		offset += int64(1)
	}
	return result
}

func ParseInt32(reader io.ReaderAt, offset int64) int32 {
	data := make([]byte, 4)
	_, err := reader.ReadAt(data, offset)
	if err != nil {
		return 0
	}
	return int32(binary.LittleEndian.Uint32(data))
}

func ParseUint16(reader io.ReaderAt, offset int64) uint16 {
	data := make([]byte, 2)
	_, err := reader.ReadAt(data, offset)
	if err != nil {
		return 0
	}
	return binary.LittleEndian.Uint16(data)
}

func ParseUint32(reader io.ReaderAt, offset int64) uint32 {
	data := make([]byte, 4)
	_, err := reader.ReadAt(data, offset)
	if err != nil {
		return 0
	}
	return binary.LittleEndian.Uint32(data)
}

func ParseUint64(reader io.ReaderAt, offset int64) uint64 {
	data := make([]byte, 8)
	_, err := reader.ReadAt(data, offset)
	if err != nil {
		return 0
	}
	return binary.LittleEndian.Uint64(data)
}

func ParseUint8(reader io.ReaderAt, offset int64) byte {
	result := make([]byte, 1)
	_, err := reader.ReadAt(result, offset)
	if err != nil {
		return 0
	}
	return result[0]
}

func ParseTerminatedString(reader io.ReaderAt, offset int64) string {
	data := make([]byte, 1024)
	n, err := reader.ReadAt(data, offset)
	if err != nil && err != io.EOF {
		return ""
	}
	idx := bytes.Index(data[:n], []byte{0})
	if idx < 0 {
		idx = n
	}
	return string(data[0:idx])
}

func ParseString(reader io.ReaderAt, offset int64, length int64) string {
	data := make([]byte, length)
	n, err := reader.ReadAt(data, offset)
	if err != nil && err != io.EOF {
		return ""
	}
	return string(data[:n])
}

func ParseTerminatedUTF16String(reader io.ReaderAt, offset int64) string {
	data := make([]byte, 1024)
	n, err := reader.ReadAt(data, offset)
	if err != nil && err != io.EOF {
		return ""
	}

	idx := bytes.Index(data[:n], []byte{0, 0})
	if idx < 0 {
		idx = n - 1
	}
	return UTF16BytesToUTF8(data[0:idx+1], binary.LittleEndian)
}

func ParseUTF16String(reader io.ReaderAt, offset int64, length int64) string {
	data := make([]byte, length)
	n, err := reader.ReadAt(data, offset)
	if err != nil && err != io.EOF {
		return ""
	}
	return UTF16BytesToUTF8(data[:n], binary.LittleEndian)
}

func UTF16BytesToUTF8(b []byte, o binary.ByteOrder) string {
	if len(b) < 2 {
		return ""
	}

	if b[0] == 0xff && b[1] == 0xfe {
		o = binary.BigEndian
		b = b[2:]
	} else if b[0] == 0xfe && b[1] == 0xff {
		o = binary.LittleEndian
		b = b[2:]
	}

	utf := make([]uint16, (len(b)+(2-1))/2)

	for i := 0; i+(2-1) < len(b); i += 2 {
		utf[i/2] = o.Uint16(b[i:])
	}
	if len(b)/2 < len(utf) {
		utf[len(utf)-1] = utf8.RuneError
	}

	return string(utf16.Decode(utf))
}
